info:
  # Root URL where the site will be published
  url:         http://willkoehler.net

  # Blog Information
  title:        "Will Koehler"
  subtitle:     "Independent web developer living in Columbus, OH"
  cover_image:  short-north-columbus-oh.jpg
  cover_image_caption: "Short North, Columbus, OH. Photo: Pineapple XVI"
  about_image:  goodale-park-columbus-oh.jpg
  about_image_caption: "Goodale Park, Columbus, OH. Photo: Dave K."
  logo:         logo.png
  
  # Company information
  company:      Will Koehler
  company_url:  /
  # facebook:     sendtoinc
  twitter:      wckoehler
  github:       willkoehler
  # gplus:        '101183822199340201470'
  
  # Product Information
  # product_link: http://incorporated.sendtoinc.com/
  # tagline:      "Get a modern blog for your company"
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false
  
  # Sharing settings
  sharing:
    twitter:    false
    facebook:   false
    gplus:      false
    hn:         false
    
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  # google_font: 'Droid+Sans:400,700'
  
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

relative_permalinks:  true
paginate:             10
excerpt_separator:    "<!-- more -->"

# safe mode must be disabled to use jekyll-assets.
safe:               false

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false